-- MENU CONFIGURATION (ADD TO MENU)
INSERT INTO MENU_ITEMS([SITE], CATEGORY, MENU, TITLE, URL, WIDTH, HEIGHT, POPUP)
SELECT S.[SITE], 'REPORTS' AS CATEGORY, 'RPTCSCMJBS' AS MENU, 'Completed Jobs Report' AS TITLE, 'reports/RPT_CSFB_Completed_Jobs.ASPX' AS URL, 800 AS WIDTH, 600 AS HEIGHT, 1 AS POPUP FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE], 'REPORTS' AS CATEGORY, 'RPTCSDLAUD' AS MENU, 'Daily Audit Report' AS TITLE, 'reports/RPT_CSFB_DAILY_AUDIT.aspx' AS URL, 1000 AS WIDTH, 600 AS HEIGHT, 1 AS POPUP FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE], 'REPORTS' AS CATEGORY, 'RPTCSPERSO' AS MENU, 'Personnel Report' AS TITLE, 'reports/RPT_CSFB_Personnel.ASPX' AS URL, 800 AS WIDTH, 600 AS HEIGHT, 1 AS POPUP FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE], 'REPORTS' AS CATEGORY, 'RPTTIMEEST' AS MENU, 'Time Estimation Report' AS TITLE, 'reports/RPT_CSFB_Time_Estimation.ASPX' AS URL, 1000 AS WIDTH, 600 AS HEIGHT, 1 AS POPUP FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE], 'REPORTS' AS CATEGORY, 'RPTCSWORKF' AS MENU, 'Workflow Report' AS TITLE, 'reports/RPT_CSFB_Workflow.ASPX' AS URL, 1000 AS WIDTH, 600 AS HEIGHT, 1 AS POPUP FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE], 'REPORTS' AS CATEGORY, 'RBTCSMTI' AS MENU, 'Main Ticket Info' AS TITLE, 'REPORTS/RPT_CSFB_MAIN_TICKET_INFO.ASPX' AS URL, 1100 AS WIDTH, 600 AS HEIGHT, 1 AS POPUP FROM SITES S WHERE S.ENABLED = 1


-- ROLE CONFIGURATION (ADD TO SYSADMIN & SITEADMIN ROLES)
INSERT INTO ROLE_ITEMS([SITE],[ROLE],CATEGORY, MENU, [ENABLED])
SELECT S.[SITE],'SYSADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSCMJBS' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SYSADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSDLAUD' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SYSADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSPERSO' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SYSADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTTIMEEST' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SYSADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSWORKF' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SYSADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RBTCSMTI' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SITEADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSCMJBS' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SITEADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSDLAUD' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SITEADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSPERSO' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SITEADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTTIMEEST' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SITEADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RPTCSWORKF' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1
UNION ALL
SELECT S.[SITE],'SITEADMIN' AS [ROLE],'REPORTS' AS CATEGORY, 'RBTCSMTI' AS MENU, 1 AS ENABLED FROM SITES S WHERE S.ENABLED = 1



